### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by novas0x2a** [newrelic/nri-redis#109]
## Feature Description
We'd like TLS connection support

## Describe Alternatives
There are none.

## Additional context
This is already supported by the upstream lib (https://github.com/gomodule/redigo) though, note that the code is currently using https://github.com/garyburd/redigo, which is the archived old version of the same lib.

## Priority
Blocker (our redis instances require encryption in flight)

**Comment by hammady** [comment]
I'm glad this was reported already and even accepted as a feature. Is there any rough estimate on when it will be released? I am currently considering multiple options for redis monitoring (Prometheus exporting, this one, and a proxy that terminates TLS). This one is the cleanest approach, but the timing is also important. I can even help in coding/reviewing the required changes as I already have experience introducing TLS for a go tool I am working on that uses [go-redis](https://github.com/go-redis/redis).

**Comment by heaje** [comment]
I didn't realize this issue existed until just now, but I just submitted a PR that adds this functionality.  See #118.

**Comment by paologallinaharbur** [comment]
The feature is now supported! Let us know if you face any issues

**Comment by hammady** [comment]
> The feature is now supported! Let us know if you face any issues

Many thanks for getting this done. For anyone coming here, please upgrade your helm chart to use nri-redis versions 1.7.0+.

**Comment by paologallinaharbur** [comment]
Please notice that the integration is still not bundled in the NewRelic kubernetes image. We need to bump this https://github.com/newrelic/infrastructure-bundle/blob/master/bundle.yml and then release all the images. Likely we are going to release this together with different integration updates
