### ISSUE TITLE
Redis "CONFIG" Command Is Renamed Causing NRI's config_inventory to Fail

### ISSUE THREAD

**Issue by williamchanrico** [newrelic/nri-redis#114]
## Is your feature request related to a problem? Please describe.

Hi, we are starting to use NRI Redis in Tokopedia and our Redis are configured with:

```
rename-command CONFIG "ZmtlbmZ3ZWZl-CONFIG"
```

We are renaming redis-cli "CONFIG" command to avoid people/clients doing destructive CONFIG change on-the-fly. E.g. enabling AOF on the fly could pressure disk iops, etc.

Does it makes sense to make this [CONFIG](https://github.com/newrelic/nri-redis/blob/0e426a97438135950aa7c1e14136786b387ea71b/src/connection.go#L79) key configurable?
![image](https://user-images.githubusercontent.com/13122042/125068354-94942e00-e0df-11eb-94e9-d413cc7e5120.png)

## Feature Description
A clear and concise description of the feature you want or need.

Configurable Redis "CONFIG" sub-command used by nri-redis to get Redis configurations when we enable `config_inventory: True`. 

[Documentation](https://docs.newrelic.com/docs/integrations/host-integrations/host-integrations-list/redis-monitoring-integration/)
![image](https://user-images.githubusercontent.com/13122042/125068501-be4d5500-e0df-11eb-80e2-62a23625fa30.png)

## Describe Alternatives
A clear and concise description of any alternative solutions or features you've considered. Are there examples you could link us to?

## Additional context

Tokopedia is moving Redis metrics and logging (everything!) to NR.

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Nice to Have, Really Want, Must Have, Blocker] 

Umm.. Really Want

We want to avoid maintaining a separate fork of nri-redis.

**Comment by gsanchezgavier** [comment]
Thanks @williamchanrico for submitting this FR, we will include it in our prioritization round, looks like something simple to implement.
Where you willing to submit a PR for this? to avoid the fork?
