### ISSUE TITLE
Fix hostname argument handling to support IPv6 address family

### ISSUE THREAD

**Issue by ibirisol** [newrelic/nri-redis#120]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )
When an IPv6 address is input to the NRI, it does not format as expected by the connector handler (redis.Dial). Instead, it needs to be formatted as defined in RFC 2732.

```
time="2021-07-23T19:53:24Z" level=warning msg="integration exited with error state" component=integrations.runner.Runner env=production error="exit status 2" integration_name=nri-redis stderr="[FATAL] can't continue: Redis connection through TCP failed, got error: dial tcp: address fd30:0:0:30::230:6379: too many colons in address\npanic: Redis connection through TCP failed, got error: dial tcp: address fd30:0:0:30::230:6379: too many colons in address\n\ngoroutine 1 [running]:\ngithub.com/newrelic/nri-redis/vendor/github.com/newrelic/infra-integrations-sdk/log.Fatal(0x741b00, 0xc42007c820)\n\t/go/src/github.com/newrelic/nri-redis/vendor/github.com/newrelic/infra-integrations-sdk/log/log.go:107 +0xd5\nmain.main()\n\t/go/src/github.com/newrelic/nri-redis/src/redis.go:63 +0x84d"
```

## Expected Behavior

Connect to a remote entity (host) using IPv6 to retrieve metrics.

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

Execute command to a Redis over IPv6 as shown below.

```
$ nri-redis -hostname ::1
```

**Comment by ibirisol** [comment]
add support to IPv6 address family as hostname argument (#121)

**Comment by paologallinaharbur** [comment]
fixed
