### ISSUE TITLE
Redis commandstats metrics

### ISSUE THREAD

**Issue by andypmw** [newrelic/nri-redis#141]
## Is your feature request related to a problem? Please describe.
Maintaining and debugging Redis (and Redis Cluster) on production environment will be pleasant if we can see statistics of how much each Redis commands called. The Redis Server has an internal command statistics. We can get it by using `INFO commandstats` command.

Example:
```
127.0.0.1:6379> INFO commandstats
# Commandstats
cmdstat_config:calls=1,usec=23,usec_per_call=23.00,rejected_calls=0,failed_calls=0
cmdstat_client:calls=177,usec=431,usec_per_call=2.44,rejected_calls=2,failed_calls=0
cmdstat_cluster:calls=184,usec=8919,usec_per_call=48.47,rejected_calls=0,failed_calls=0
cmdstat_latency:calls=177,usec=461,usec_per_call=2.60,rejected_calls=0,failed_calls=0
cmdstat_auth:calls=407,usec=6638,usec_per_call=16.31,rejected_calls=0,failed_calls=224
cmdstat_ping:calls=3,usec=2,usec_per_call=0.67,rejected_calls=0,failed_calls=0
cmdstat_command:calls=2,usec=1867,usec_per_call=933.50,rejected_calls=1,failed_calls=0
cmdstat_info:calls=183,usec=20578,usec_per_call=112.45,rejected_calls=6,failed_calls=0
cmdstat_slowlog:calls=354,usec=979,usec_per_call=2.77,rejected_calls=0,failed_calls=0
cmdstat_readonly:calls=3,usec=1,usec_per_call=0.33,rejected_calls=0,failed_calls=0
```

## Feature Description
The nri-redis will be much better if it is able to capture the commandstats metrics. So my company will be able to display the detailed command-calls on New Relic dashboard.

## Describe Alternatives
FYI, the `redis_exporter` for Prometheus already exported the metrics, reference:
https://github.com/oliver006/redis_exporter/blob/3e7d7546638b66e1ecba7ddf8c35ca99934c7a6e/exporter/info.go#L88

## Additional context
Redis Cluster production. By checking and comparing the commandstats on each redis-node, our administrator can check any is any redis-cluster balanced or not.

## Priority
Nice to Have.

**Comment by alvarocabanas** [comment]
We appreciate you taking the time to bring this to our attention.

It will be taken into account in future quarters.
