### ISSUE TITLE
keyspaceHitsPerSecond and other "Per Second" metrics report incorrect values and report inconsistently 

### ISSUE THREAD

**Issue by rjduffner** [newrelic/nri-redis#36]
##### Description of the problem

When attempting to use keyspaceHitsPerSecond from the RedisSample, we noticed that the reported value is not the rate (per second) but it is the raw count of hits against the instance since the instance was started. (It matches the keyspace_hits key from the INFO command)

Also, for some reason this metric is not always reported yet other metrics in the RedisSample (Fragmentation Ratio for example) are always reported.

Am I missing something about these keys?

The first screen shot is the timeseries of hits we are seeing in NewRelic. The Second screen shot is the application's perspective where we are seeing they are processing about 20-30 "items" per X time. Yet you can see that the first screen shot shows the hits as 0. For an item to be processed by the app, it has to retrieve a key from Redis. The third screen shot shows that while the rate is not being populated, other metrics from the sample are.

![Screen Shot 2019-03-13 at 2 41 17 PM](https://user-images.githubusercontent.com/4734568/54316646-7add8d00-459e-11e9-8722-9d2d44b6c959.png)

![Screen Shot 2019-03-13 at 2 41 26 PM](https://user-images.githubusercontent.com/4734568/54316649-7dd87d80-459e-11e9-9ae7-ac3621b5a3c1.png)

![Screen Shot 2019-03-13 at 2 43 52 PM](https://user-images.githubusercontent.com/4734568/54316656-80d36e00-459e-11e9-9fbd-ffac20ee6ede.png)

##### OS

- [ ] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [x] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by xino12** [comment]
Can you show me the query of the timeseries graph please? 

This is an example of a query I've done myself.
FROM RedisSample SELECT average(db.keyspaceHitsPerSecond) TIMESERIES

<img width="705" alt="Screen Shot 2019-03-27 at 10 13 00" src="https://user-images.githubusercontent.com/1876430/55063742-f6e4d400-5078-11e9-8154-66cca0550036.png">

Thanks

**Comment by rjduffner** [comment]
![Screen Shot 2019-03-27 at 12 46 21 PM](https://user-images.githubusercontent.com/4734568/55107370-5f8a7b80-508e-11e9-9d9e-1d1e66cbc780.png)

Here is the time series graph, You can see that the scales are still way off.

**Comment by xino12** [comment]
Which redis and integration version are you using? Let's see if I'm able to reproduce it and fix the bug that seems to be happening.

**Comment by rjduffner** [comment]
Hi @xino12, We are running 1.0.1-1 installed via APT
```
robertd@<hostname>:/var/db/newrelic-infra/newrelic-integrations$ apt-cache policy nri-redis
nri-redis:
  Installed: 1.0.1-1
  Candidate: 1.0.1-1
```

**Comment by xino12** [comment]
And which redis version?

**Comment by rjduffner** [comment]
Sorry about that, Redis Version 3.0.6

**Comment by rjduffner** [comment]
kk Thanks @xino12
