### ISSUE TITLE
`masterauth` password included in inventory

### ISSUE THREAD

**Issue by rabbitt** [newrelic/nri-redis#41]
##### `masterauth` password included in inventory

Currently only `requirepass` is stripped from the inventory, but `masterauth` remains. This should be stripped as well. Expect a PR shortly.

##### OS

- [x] All of them
- [ ] Amazon Linux, all versions
- [ ] CentOS, version 6 or higher
- [ ] Debian, version 7 ("Wheezy") or higher
- [ ] Red Hat Enterprise Linux (RHEL), version 6 or higher
- [ ] Ubuntu, versions 12.04, 14.04, and 16.04 (LTS  versions)
- [ ] Windows Server, 2008 and 2012 and their service packs

**Comment by rabbitt** [comment]
@xino12 Any chance you, or someone else, could look at this soon? This is honestly kind of a critical issue here as people using replication will have their `requirepass` exposed in NewRelic inventory through the `masterauth` config...

**Comment by mariomac** [comment]
Hi @rabbitt , thank you for your contribution. We are looking into your patch and provide a release soon.

**Comment by mariomac** [comment]
Redis Integration v1.2.1 has been released. Thank you for your collaboration.

**Comment by rabbitt** [comment]
Hi @mariomac, If I can find time to finish it, I'll have another feature soon too - wildcard `keys` that must both respect `key_limit` and be prefixed with a string >= 1 character (e.g., `keys: '["foo:*", "bar", "baz", "neato:123:*"]`)

**Comment by tormodmacleod** [comment]
> Hi @mariomac, If I can find time to finish it, I'll have another feature soon too - wildcard `keys` that must both respect `key_limit` and be prefixed with a string >= 1 character (e.g., `keys: '["foo:*", "bar", "baz", "neato:123:*"]`)

@rabbitt did you ever get anywhere with this? being able to use wildcards would be a great workaround for https://github.com/hashicorp/terraform-provider-helm/issues/1292
