### ISSUE TITLE
Many problems when building from the scratch

### ISSUE THREAD

**Issue by vongosling** [newrelic/nri-redis#84]
1. === redis === [ validate ]: running gofmt... failed. Incorrect syntax in the following files:
src/inventory_test.go src/metrics_test.go
make: *** [Makefile:31: validate-only] Error 1

This is the first problem.

2.  when I remove the validate-only task in the makefile, the following error is :

=== redis === [ validate-deps ]: installing validation dependencies...
go: github.com/Sirupsen/logrus@v0.11.5: parsing go.mod:
        module declares its path as: github.com/sirupsen/logrus
                but was required as: github.com/Sirupsen/logrus
make: *** [Makefile:24: validate-deps] Error 1

I think you should update helplers.go module import to the latest version sirupsen, while not Sirupsen.

3. When I update like above, I also happen to many vendor dependency update warnings. At this time, I remove the directory vendor and make it passed. So, My question is could we remove the vendor dependency and use go mod style? I could use this way to build when I remove validate-only in the makefile and remove vendor directory.

p.s. If the demo could not build smoothly from the scratch, I could not figure out how do we ensure and convince our customers to use it?

**Comment by carlosroman** [comment]
We are addressing the build issues and hope to soon release something soon. The PR #60 has a lot of work gone into it to make sure the build is more reproducible. We've gone through the Makefile to simplify it and remove steps that were no longer needed.

As for moving to `go.mod`, at the moment we can't as we have to support `go 1.9`. In the future we hope to be able to switch to `go.mod`. The [infrastructure agent](https://github.com/newrelic/infrastructure-agent) has already moved to `go.mod` and kept support for `go 1.9` so we have a patter we can use.

**Comment by brushknight** [comment]
Hello! We migrated to public build last October. This PR #60 was merged. Now we release from GH, so I guess all issues with building from scratch should be resolved.
